<?php

declare(strict_types=1);

use App\Controllers\PageController;
use App\Controllers\RbacController;
use App\Core\Router;

/** @var Router $router */

$router->get('/robots.txt', [PageController::class, 'robots']);
$router->get('/sitemap.xml', [PageController::class, 'sitemap']);
$router->get('/pengurusan-akses', [RbacController::class, 'index']);
$router->get('/about', [PageController::class, 'page_about']);
$router->get('/analisis-pat-t4-uasa-t1,2,3', [PageController::class, 'page_analisis_pat_t4_uasa_t1_2_3']);
$router->get('/analisis-ppt', [PageController::class, 'page_analisis_ppt']);
$router->get('/bank-soalan-uasa-ppt-pat-selaras', [PageController::class, 'page_bank_soalan_uasa_ppt_pat_selaras']);
$router->get('/bil-kelas-gambar', [PageController::class, 'page_bil_kelas_gambar']);
$router->get('/buletin-sekolah', [PageController::class, 'page_buletin_sekolah']);
$router->get('/contact', [PageController::class, 'page_contact']);
$router->post('/contact', [PageController::class, 'page_contact']);
$router->get('/courses', [PageController::class, 'page_courses']);
$router->get('/cuti-perayaan', [PageController::class, 'page_cuti_perayaan']);
$router->get('/enrolmen-murid', [PageController::class, 'page_enrolmen_murid']);
$router->get('/guru-apk', [PageController::class, 'page_guru_apk']);
$router->get('/jawatankuasa-pibg', [PageController::class, 'page_jawatankuasa_pibg']);
$router->get('/kalendar-akademik', [PageController::class, 'page_kalendar_akademik']);
$router->get('/kecemerlangan-program-akademik', [PageController::class, 'page_kecemerlangan_program_akademik']);
$router->get('/kelab-persatuan', [PageController::class, 'page_kelab_persatuan']);
$router->get('/keputusan', [PageController::class, 'page_keputusan']);
$router->get('/lencana-lagu-sekolah', [PageController::class, 'page_lencana_lagu_sekolah']);
$router->get('/maklumat-pbd-panduan', [PageController::class, 'page_maklumat_pbd_panduan']);
$router->get('/misi-visi-sekolah', [PageController::class, 'page_misi_visi_sekolah']);
$router->get('/news-details', [PageController::class, 'page_news_details']);
$router->get('/news', [PageController::class, 'page_news']);
$router->get('/pbd-ppt', [PageController::class, 'page_pbd_ppt']);
$router->get('/pbd-ppt-tingkatan-1', [PageController::class, 'page_pbd_ppt_tingkatan_1']);
$router->get('/pbd-ppt-tingkatan-2', [PageController::class, 'page_pbd_ppt_tingkatan_2']);
$router->get('/pbd-ppt-tingkatan-3', [PageController::class, 'page_pbd_ppt_tingkatan_3']);
$router->get('/pbd-ppt-tingkatan-4', [PageController::class, 'page_pbd_ppt_tingkatan_4']);
$router->get('/pbd-ppt-tingkatan-5', [PageController::class, 'page_pbd_ppt_tingkatan_5']);
$router->get('/pbd-penjaminan-kualiti', [PageController::class, 'page_pbd_penjaminan_kualiti']);
$router->get('/pbd-pk-pemantauan', [PageController::class, 'page_pbd_pk_pemantauan']);
$router->get('/pbd-pk-pementoran', [PageController::class, 'page_pbd_pk_pementoran']);
$router->get('/pbd-pk-pengesanan', [PageController::class, 'page_pbd_pk_pengesanan']);
$router->get('/pbd-pk-penyelarasan', [PageController::class, 'page_pbd_pk_penyelarasan']);
$router->get('/pbd-uasa', [PageController::class, 'page_pbd_uasa']);
$router->get('/pbd-uasa-individu', [PageController::class, 'page_pbd_uasa_individu']);
$router->get('/pbd-ppt-tingkatan-1-individu', [PageController::class, 'page_pbd_ppt_tingkatan_1_individu']);
$router->get('/pbd-ppt-tingkatan-2-individu', [PageController::class, 'page_pbd_ppt_tingkatan_2_individu']);
$router->get('/pbd-ppt-tingkatan-3-individu', [PageController::class, 'page_pbd_ppt_tingkatan_3_individu']);
$router->get('/pbd-ppt-tingkatan-4-individu', [PageController::class, 'page_pbd_ppt_tingkatan_4_individu']);
$router->get('/pbd-ppt-tingkatan-5-individu', [PageController::class, 'page_pbd_ppt_tingkatan_5_individu']);
$router->get('/pelan-sekolah', [PageController::class, 'page_pelan_sekolah']);
$router->get('/pemimpin-murid', [PageController::class, 'page_pemimpin_murid']);
$router->get('/penggubal-soalan-upsa-uasa', [PageController::class, 'page_penggubal_soalan_upsa_uasa']);
$router->get('/pengurusan-tertinggi', [PageController::class, 'page_pengurusan_tertinggi']);
$router->get('/pentaksiran-peperiksaan', [PageController::class, 'page_pentaksiran_peperiksaan']);
$router->get('/peraturan-sekolah', [PageController::class, 'page_peraturan_sekolah']);
$router->get('/pilihan-mata-pelajaran', [PageController::class, 'page_pilihan_mata_pelajaran']);
$router->get('/pra-sekolah', [PageController::class, 'page_pra_sekolah']);
$router->get('/profil-sekolah', [PageController::class, 'page_profil_sekolah']);
$router->get('/pusat-sumber', [PageController::class, 'page_pusat_sumber']);
$router->get('/sejarah-sekolah', [PageController::class, 'page_sejarah_sekolah']);
$router->get('/senarai-pengetua', [PageController::class, 'page_senarai_pengetua']);
$router->get('/staff', [PageController::class, 'page_staff']);
$router->get('/unit-badan-beruniform', [PageController::class, 'page_unit_badan_beruniform']);
$router->get('/unit-bimbingan-kaunseling', [PageController::class, 'page_unit_bimbingan_kaunseling']);
$router->get('/unit-pbd', [PageController::class, 'page_unit_pbd']);
$router->get('/', [PageController::class, 'home']);
